// REDUX ACTION TYPES
export const CONNECT_REQUEST = 'CONNECT_REQUEST'
export const CONNECT_SUCCESS = 'CONNECT_SUCCESS'
export const CONNECT_FAILURE = 'CONNECT_FAILURE'

export const POOL_CONNECT_REQUEST = 'POOL_CONNECT_REQUEST'
export const POOL_CONNECT_SUCCESS = 'POOL_CONNECT_SUCCESS'
export const POOL_CONNECT_FAILURE = 'POOL_CONNECT_FAILURE'

export const TX_REQUEST = 'TX_REQUEST'
export const TX_LIST_SUCCESS = 'TX_LIST_SUCCESS'
export const TX_ADD_SUCCESS = 'TX_ADD_SUCCESS'
export const TX_FAILURE = 'TX_FAILURE'

export const DONOR_REQUEST = 'DONOR_REQUEST'
export const DONOR_LIST_SUCCESS = 'DONOR_LIST_SUCCESS'
export const DONOR_FAILURE = 'DONOR_FAILURE'

export const OPEN_NOTIFICATION = 'OPEN_NOTIFICATION'
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION'